Repository everycache-group/everycache-app, pull requests merged in 2021-12, with the labels that each got.

#29 Fix up backend startup and docker-compose files
  .gitignore
  api/autoapp.py
  api/everycache_api/app.py
  api/everycache_api/auth/token_cleanup.py
  api/everycache_api/config.py
  api/everycache_api/manage.py
  api/main.bat
  api/main.sh
  dev-composition.sh
  dev.env
  docker-compose.dev.yaml
  docker-compose.override.yaml
  docker-compose.yaml
Labels: bug, enhancement

#30 Fix error handling in production environment
  api/everycache_api/api/views.py
Labels: bug

#31 Feature/procfile
  api/Procfile
Labels: enhancement
